services:
  postgres:
    image: postgres:16
    container_name: lighthouse-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lighthouse-net

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgres
    command:
      - --searchPath=/changesets
      - --changelog-file=db.changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/${DB_NAME}
      - --username=${DB_USER}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ./changelog:/changesets
    networks:
      - lighthouse-net

volumes:
  postgres_data:

networks:
  lighthouse-net:
    driver: bridge
